In [333]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [334]:
df = pd.read_csv("data/raw/space_missions.csv", encoding="latin1")

In [335]:
df.head()

,Company,Location,Date,Time,Rocket,Mission,RocketStatus,Price,MissionStatus
0,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",04-10-1957,19.28.00,Sputnik 8K71PS,Sputnik-1,Retired,NaN,Success
1,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",03-11-1957,2.30.00,Sputnik 8K71PS,Sputnik-2,Retired,NaN,Success
2,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",06-12-1957,16.44.00,Vanguard,Vanguard TV3,Retired,NaN,Failure
3,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA",01-02-1958,3.48.00,Juno I,Explorer 1,Retired,NaN,Success
4,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",05-02-1958,7.33.00,Vanguard,Vanguard TV3BU,Retired,NaN,Failure

In [336]:
df.tail()

,Company,Location,Date,Time,Rocket,Mission,RocketStatus,Price,MissionStatus
4625,SpaceX,"SLC-4E, Vandenberg SFB, California, USA",22-07-2022,17.39.00,Falcon 9 Block 5,Starlink Group 3-2,Active,67,Success
4626,CASC,"LC-101, Wenchang Satellite Launch Center, China",24-07-2022,6.22.00,Long March 5B,Wentian,Active,NaN,Success
4627,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA",24-07-2022,13.38.00,Falcon 9 Block 5,Starlink Group 4-25,Active,67,Success
4628,CAS Space,"Jiuquan Satellite Launch Center, China",27-07-2022,4.12.00,Zhongke-1A,Demo Flight,Active,NaN,Success
4629,CASC,"LC-3, Xichang Satellite Launch Center, China",29-07-2022,13.28.00,Long March 2D,Yaogan 35 Group 03,Active,29.75,Success

In [337]:
df.sample(5)

,Company,Location,Date,Time,Rocket,Mission,RocketStatus,Price,MissionStatus
2177,RVSN USSR,"Site 32/2, Plesetsk Cosmodrome, Russia",05-03-1985,15.39.00,Tsyklon-3,Cosmos 1633,Retired,NaN,Success
2435,Arianespace,"ELA-2, Guiana Space Centre, French Guiana, France",05-06-1989,22.37.00,Ariane 44L,"Superbird-A, DFS-1",Retired,NaN,Success
4277,VKS RF,"Site 43/3, Plesetsk Cosmodrome, Russia",20-02-2020,8.24.00,Soyuz 2.1a/Fregat-M,Meridian-M nâ Â­19L,Active,23,Success
2057,General Dynamics,"SLC-36A, Cape Canaveral AFS, Florida, USA",19-05-1983,22.26.00,Atlas-SLV3D Centaur-D1AR,Intelsat V -506,Retired,NaN,Success
3369,ISAS,"Mu Pad, Uchinoura Space Center, Japan",10-07-2005,3.30.00,Mu-V / M-25,Suzaku,Retired,NaN,Success

In [338]:
#dataset shape
print(f"Rows : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

Rows : 4630
Columns : 9

In [339]:
df.columns

Index(['Company', 'Location', 'Date', 'Time', 'Rocket', 'Mission',
       'RocketStatus', 'Price', 'MissionStatus'],
      dtype='object')

In [340]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4630 entries, 0 to 4629
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Company        4630 non-null   object
 1   Location       4630 non-null   object
 2   Date           4630 non-null   object
 3   Time           4503 non-null   object
 4   Rocket         4630 non-null   object
 5   Mission        4630 non-null   object
 6   RocketStatus   4630 non-null   object
 7   Price          1265 non-null   object
 8   MissionStatus  4630 non-null   object
dtypes: object(9)
memory usage: 325.7+ KB

In [341]:
df.isnull().sum()

Company             0
Location            0
Date                0
Time              127
Rocket              0
Mission             0
RocketStatus        0
Price            3365
MissionStatus       0
dtype: int64

In [342]:
print(df["Price"].dtype)

object

In [343]:
print(df["Time"].dtype)

object

In [344]:
df["Price"] = pd.to_numeric(df["Price"], errors="coerce")

In [345]:
# Calculate company-wise mean price
company_mean = df.groupby("Company")["Price"].transform("mean")

# Fill missing prices
df["Price"] = df["Price"].fillna(company_mean)

# Fill any remaining missing values with the overall mean
df["Price"] = df["Price"].fillna(df["Price"].mean())

In [346]:
df.isnull().sum()

Company            0
Location           0
Date               0
Time             127
Rocket             0
Mission            0
RocketStatus       0
Price              0
MissionStatus      0
dtype: int64

In [347]:
df["Time"].head(20)

0     19.28.00
1      2.30.00
2     16.44.00
3      3.48.00
4      7.33.00
5     18.27.00
6     12.15.00
7     17.38.00
8      9.01.00
9      2.53.00
10     7.12.00
11     3.46.00
12     5.00.00
13         NaN
14    15.00.00
15         NaN
16    12.18.00
17         NaN
18     6.17.00
19         NaN
Name: Time, dtype: object

In [348]:
df.isnull().sum()

Company            0
Location           0
Date               0
Time             127
Rocket             0
Mission            0
RocketStatus       0
Price              0
MissionStatus      0
dtype: int64

In [349]:
# Check missing values
print(df["Time"].isnull().sum())

# Remove rows where Time is missing
df = df.dropna(subset=["Time"])

# Reset index
df.reset_index(drop=True, inplace=True)

# Verify
print(df["Time"].isnull().sum())
print(df.shape)

127
0
(4503, 9)

In [350]:
# Convert Time from HH.MM.SS to HH:MM:SS

df["Time"] = (
    df["Time"]
    .astype(str)
    .str.replace(".", ":", regex=False)
)
df.head()

,Company,Location,Date,Time,Rocket,Mission,RocketStatus,Price,MissionStatus
0,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",04-10-1957,19:28:00,Sputnik 8K71PS,Sputnik-1,Retired,108.84232,Success
1,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",03-11-1957,2:30:00,Sputnik 8K71PS,Sputnik-2,Retired,108.84232,Success
2,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",06-12-1957,16:44:00,Vanguard,Vanguard TV3,Retired,108.84232,Failure
3,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA",01-02-1958,3:48:00,Juno I,Explorer 1,Retired,108.84232,Success
4,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA",05-02-1958,7:33:00,Vanguard,Vanguard TV3BU,Retired,108.84232,Failure

In [351]:
for col in df.columns:
    print(col)
    print(df[col].nunique())
    print("-"*40)

Company
61
----------------------------------------
Location
154
----------------------------------------
Date
4077
----------------------------------------
Time
1300
----------------------------------------
Rocket
358
----------------------------------------
Mission
4449
----------------------------------------
RocketStatus
2
----------------------------------------
Price
76
----------------------------------------
MissionStatus
4
----------------------------------------

In [352]:
#Total Missions
len(df)

4503

In [353]:
#Number of Companies
df["Company"].nunique()

61

In [354]:
#Number of Rockets
df["Rocket"].nunique()

358

In [355]:
#Number of Launch Locations
df["Location"].nunique()

154

In [356]:
#Mission Status Distribution
df["MissionStatus"].value_counts()

MissionStatus
Success              4076
Failure               318
Partial Failure       107
Prelaunch Failure       2
Name: count, dtype: int64

In [357]:
#Rocket Status Distribution
df["RocketStatus"].value_counts()

RocketStatus
Retired    3512
Active      991
Name: count, dtype: int64

In [358]:
#creating backup
df_original = df.copy()

In [359]:
# ============================================================
# Export Clean Dataset
# ============================================================

# Save cleaned dataset for further analysis
df.to_csv(
    "outputs/cleaned_dataset.csv",
    index=False
)

print("Clean dataset exported successfully.")

Clean dataset exported successfully.